### ISSUE TITLE
"Compute Missing/Stale Covidcast Direction" job dies on missed data_stdevs key

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#120]
The database has a 32-character limit on the length of signal names. This is irregularly enforced, and it causes Automation to fail when the limit is transgressed.

Signal names are stored in the `data_stdevs[source][signal]` dictionary exactly as they are read from an ingested filename. When they are inserted into the database, they get truncated to 32 characters. The "Compute Missing/Stale Covidcast Direction" job reads signal names out of the database and expects to find them in the `data_stdevs[source][signal]` dictionary, but the truncated names are not listed there. The job fails with a KeyError:

```python
Traceback (most recent call last):
  File "/home/automation/.pyenv/versions/3.4.10/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/automation/.pyenv/versions/3.4.10/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/automation/driver/delphi/epidata/acquisition/covidcast/direction_updater.py", line 189, in <module>
    main(get_argument_parser().parse_args())
  File "/home/automation/driver/delphi/epidata/acquisition/covidcast/direction_updater.py", line 177, in main
    update_loop_impl(database)
  File "/home/automation/driver/delphi/epidata/acquisition/covidcast/direction_updater.py", line 137, in update_loop
    data_stdev = data_stdevs[source][signal][geo_type]
KeyError: 'wip_confirmed_7day_avg_cumulativ'
```

We should either extend the character limit in the database schema (perhaps at the same time we add in issue dates), or truncate the signal name after it gets read out of the filename and before it gets loaded into `data_stdevs[source][signal]`.

**Comment by krivard** [comment]
Direction is being removed, so this is no longer a problem.
