### ISSUE TITLE
Update Twitter Data [delphi.epidata.acquisition.twtr.twitter_update] failing in Automation

### ISSUE THREAD

**Issue by korlaxxalrok** [cmu-delphi/delphi-epidata#381]
`Update Twitter Data` has been consistently failing in Automation:

```
Starting step [id=24183|step_id=20|name=<span class="tag_research"> </span>Update Twitter Data]
   Running cmd...
Traceback (most recent call last):
  File "/home/automation/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/automation/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/automation/driver/delphi/epidata/acquisition/twtr/twitter_update.py", line 119, in <module>
    run()
  File "/home/automation/driver/delphi/epidata/acquisition/twtr/twitter_update.py", line 98, in run
    ht = HealthTweets(*secrets.healthtweets.login)
  File "/home/automation/driver/delphi/epidata/acquisition/twtr/healthtweets.py", line 65, in __init__
    token = self._get_token(response.text)
  File "/home/automation/driver/delphi/epidata/acquisition/twtr/healthtweets.py", line 142, in _get_token
    hidden = PageParser.filter_all(page, [('html',), ('body',), ('div',), ('div',), ('div',), ('form',), ('input',)])
  File "/home/automation/driver/delphi/epidata/acquisition/twtr/pageparser.py", line 48, in filter_all
    node = PageParser.filter(node, *f)
  File "/home/automation/driver/delphi/epidata/acquisition/twtr/pageparser.py", line 55, in filter
    for node in node['nodes']:
TypeError: 'NoneType' object is not subscriptable
Checking dates between 2020-11-30 and 2021-01-18...
   Fail [cmd=python3 -m delphi.epidata.acquisition.twtr.twitter_update]

**Comment by krivard** [comment]
Healthtweets.org stopped updating in December 2020:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/1158666/217083373-0b4ae460-a0d8-4835-b677-71dc236c5f48.png">

We should archive this pipeline, but continue to provide access to the dataset:
- [ ] tag source with final version of this code
- [ ] delete `acquisition/twtr`
- [ ] delete twtr sections of `deploy.json` and `dev/local/setup.cfg`
- [ ] **_keep_** `twitter` database table 
- [ ] **_keep_** `twtr` endpoints in `server`, `client`, `docs`, etc
