### ISSUE TITLE
exception for public health lab data

### ISSUE THREAD

**Issue by undefx** [cmu-delphi/delphi-epidata#5]
The scraper raises an exception for public health lab data saying that the header row has changed. I temporarily disabled scraping [here](https://github.com/cmu-delphi/delphi-epidata/commit/5a17eaa7da465989fb918d3855336157c680f1fe).

Stack trace (some info stripped):
```
Traceback (most recent call last):

  [...]

  File ".../epidata/acquisition/fluview/fluview_update.py", line 541, in <module>
    main()
  File ".../epidata/acquisition/fluview/fluview_update.py", line 538, in main
    update_from_file_public(issue, date, filename, test_mode=args.test)
  File ".../epidata/acquisition/fluview/fluview_update.py", line 390, in update_from_file_public
    data = [get_public_data(row) for row in rows]
  File ".../epidata/acquisition/fluview/fluview_update.py", line 390, in <listcomp>
    data = [get_public_data(row) for row in rows]
  File ".../epidata/acquisition/fluview/fluview_update.py", line 267, in get_public_data
    raise Exception('header row has changed for public health lab data.')
Exception: header row has changed for public health lab data.
```

Please take a look at your convenience.

**Comment by brookslogan** [comment]
This issue was resolved by pull request #6.
